use_frameworks!
platform :ios, ‘8.0’
target “WTKMVVMRxSwift” do


pod 'RxSwift', '~> 3.0.1’
pod 'RxCocoa', '~> 3.0.1’
pod 'RxDataSources', '~> 1.0.0'
pod 'RxOptional', '~> 3.1.3'

pod 'SnapKit', '~> 3.1.2'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'
pod 'Alamofire', '~> 4.3.0'
pod 'IQKeyboardManager', '~> 4.0.8'
end
